#!/usr/bin/env python3
"""Merge HelmRelease values with valuesFrom placeholders.

Reads a HelmRelease YAML document from stdin, merges spec.values with
placeholder values for every spec.valuesFrom entry, and writes the merged
values to stdout.

If a valuesFrom entry references a Secret (kind: Secret), the target paths
are automatically injected with "check-placeholder" since secrets are not
available in dry-run context.
"""
import sys

import yaml


def set_path(values: dict, path: str, value: str) -> None:
    parts = path.split(".")
    current = values
    for part in parts[:-1]:
        current = current.setdefault(part, {})
    current[parts[-1]] = value


def main() -> int:
    doc = yaml.safe_load(sys.stdin.read())
    values = doc.get("spec", {}).get("values") or {}
    if not isinstance(values, dict):
        values = {}

    for item in doc.get("spec", {}).get("valuesFrom") or []:
        target = item.get("targetPath")
        if target:
            # Auto-inject placeholder for any valuesFrom target path.
            # This handles both ConfigMap and Secret references — secrets
            # won't be available in dry-run, and ConfigMaps may also be
            # generated by controllers.
            set_path(values, target, "check-placeholder")

    yaml.safe_dump(values, sys.stdout, sort_keys=False)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
